# railway.toml – Laravel 12 + Vite on Railway (Nixpacks)

[build]
# Install PHP deps, then Node dev deps, then build assets with Vite
buildCommand = """
composer install --no-interaction --prefer-dist --optimize-autoloader \
&& npm ci --include=dev \
&& node node_modules/vite/bin/vite.js build
"""

[deploy]
# Prepare app then start PHP built-in server (simple production setup)
startCommand = """
php artisan migrate --force || true \
&& php artisan storage:link || true \
&& php artisan config:cache && php artisan route:cache && php artisan view:cache \
&& php -S 0.0.0.0:$PORT -t public
"""
restartPolicyType = "ON_FAILURE"
