<?php

namespace DoctrineProxies\__CG__\App\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Domain\Entities\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'books' => [parent::class, 'books', null, 8],
        "\0".'*'."\0".'created_at' => [parent::class, 'created_at', null, 8],
        "\0".'*'."\0".'email' => [parent::class, 'email', null, 8],
        "\0".'*'."\0".'email_verified_at' => [parent::class, 'email_verified_at', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'loans' => [parent::class, 'loans', null, 8],
        "\0".'*'."\0".'name' => [parent::class, 'name', null, 8],
        "\0".'*'."\0".'password' => [parent::class, 'password', null, 8],
        "\0".'*'."\0".'remember_token' => [parent::class, 'remember_token', null, 8],
        "\0".'*'."\0".'roles' => [parent::class, 'roles', null, 8],
        "\0".'*'."\0".'updated_at' => [parent::class, 'updated_at', null, 8],
        'books' => [parent::class, 'books', null, 8],
        'created_at' => [parent::class, 'created_at', null, 8],
        'email' => [parent::class, 'email', null, 8],
        'email_verified_at' => [parent::class, 'email_verified_at', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'loans' => [parent::class, 'loans', null, 8],
        'name' => [parent::class, 'name', null, 8],
        'password' => [parent::class, 'password', null, 8],
        'remember_token' => [parent::class, 'remember_token', null, 8],
        'roles' => [parent::class, 'roles', null, 8],
        'updated_at' => [parent::class, 'updated_at', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
