<?php

namespace DoctrineProxies\__CG__\App\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Book extends \App\Domain\Entities\Book implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'author' => [parent::class, 'author', null, 8],
        "\0".'*'."\0".'categories' => [parent::class, 'categories', null, 8],
        "\0".'*'."\0".'cover_path' => [parent::class, 'cover_path', null, 8],
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null, 8],
        "\0".'*'."\0".'description' => [parent::class, 'description', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'loans' => [parent::class, 'loans', null, 8],
        "\0".'*'."\0".'owner' => [parent::class, 'owner', null, 8],
        "\0".'*'."\0".'summary' => [parent::class, 'summary', null, 8],
        "\0".'*'."\0".'title' => [parent::class, 'title', null, 8],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null, 8],
        'author' => [parent::class, 'author', null, 8],
        'categories' => [parent::class, 'categories', null, 8],
        'cover_path' => [parent::class, 'cover_path', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 8],
        'description' => [parent::class, 'description', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'loans' => [parent::class, 'loans', null, 8],
        'owner' => [parent::class, 'owner', null, 8],
        'summary' => [parent::class, 'summary', null, 8],
        'title' => [parent::class, 'title', null, 8],
        'updatedAt' => [parent::class, 'updatedAt', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
